### ISSUE TITLE
After upgrading to 0.3, can't use with webpack directly

### ISSUE THREAD

**Issue by satazor** [iamdustan/smoothscroll#27] opened 2016-05-31 13:57 UTC
```js
import { polyfill } from 'smoothscroll-polyfill';
console.log(polyfill) // empty object

import polyfill from 'smoothscroll-polyfill';
console.log(polyfill) // empty object

import { polyfill } from 'smoothscroll-polyfill/src/smoothscroll';
console.log(polyfill) // function! works!
```

I guess the issue is that the dist file does not contain `module.exports` but only `exports`.

**Comment by stevenvachon** [comment] 2016-05-31 13:59
Agreed. https://github.com/iamdustan/smoothscroll/blob/master/dist/smoothscroll.js#L278-L280 appears to be the issue. Perhaps this would be better:
```js
if (typeof module==="object" && typeof module.exports==="object") {
  module.exports = UniqueNumber;
}
```

**Comment by jeremenichelli** [comment] 2016-05-31 14:07
Sorry, @satazor. Last night I fixed this but forgot to `npm run build`, this is now fixed in **0.3.2**, please update and let me know if the issue is no longer present.

**Comment by stevenvachon** [comment] 2016-05-31 14:08
It's working correctly now for me.

**Closed** 2016-05-31 14:14 UTC

**Comment by satazor** [comment] 2016-05-31 14:17
Same. Thanks!
